### PR TITLE
Add API with support for fake browsers

### PR DESCRIPTION
**Pull request by aslakhellesoy**
This PR introduces an API to `@cucumber/electron`. It currently has one feature - fake browsers!

A fake browser is just a small piece of HTML/DOM that can be inserted into the global DOM, and looks a bit like a real browser.

The purpose is to have a more realistic container where the application/component under test can be mounted. There is no limit to how many fake browsers can be created. You can create one per scenario, or several - typically one per *actor* in the scenario.

Creation of fake browsers is controlled from step definitions or hooks via the API:

```javascript
const { FakeBrowsers } = require('@cucumber/cucumber-electron')

Before(function () {
  this.fakeBrowsers = new FakeBrowsers()
})

Given('{word} has a fake browser with:', function (name, html) {
  const contentElement = this.fakeBrowsers.create(name)
  contentElement.innerHTML = html
  // Or mount a React app for example...
})
```

Screenshot:

fake-browser

TODO:
- [ ] Add TypeScript typings for the API

### CODE REVIEW

**Review by aurelien-reeves — CHANGES_REQUESTED** [review]
Could we add the .DS_Store files to .gitignore?

I would suggest another name for that API, like `htmlContainer`, or `domContainer`, or something like that.

Finally, that API will make the cucumber test-suite dependent of cucumber-electron. For example they won't be compatible as-is with raw cucumber-js, so in a CI for example. The developer would need to implement a different path when not using cucumber-electron. Are we agree with this?

**Comment by aslakhellesoy** [comment]
> I would suggest another name for that API, like htmlContainer, or domContainer, or something like that.

I'm not sure what you're referring to. Can you comment in the diff please?

> Finally, that API will make the cucumber test-suite dependent of cucumber-electron. For example they won't be compatible as-is with raw cucumber-js, so in a CI for example. The developer would need to implement a different path when not using cucumber-electron. Are we agree with this?

I don't understand what you mean. If users have added the `@cucumber/electron` module to their project, why is it problematic to use an API from that module?

**Comment by aslakhellesoy** [comment]
@aurelien-reeves do you mean that users won't be able to run scenarios with `cucumber-js`?

The `FakeBrowsers.js` API does not depend on electron. It does however depend on the DOM, via the `document` global object. They could use jsdom for this if they want to.

**Comment by aurelien-reeves** [comment]
> 
> 
> > I would suggest another name for that API, like htmlContainer, or domContainer, or something like that.
> 
> I'm not sure what you're referring to. Can you comment in the diff please?

I mean, is this a FakeBrowser API? With all that could be related to a browser like the window sizes, the possibility to scroll, to control the visible area, to take screenshots?

> 
> > Finally, that API will make the cucumber test-suite dependent of cucumber-electron. For example they won't be compatible as-is with raw cucumber-js, so in a CI for example. The developer would need to implement a different path when not using cucumber-electron. Are we agree with this?
> 
> I don't understand what you mean. If users have added the `@cucumber/electron` module to their project, why is it problematic to use an API from that module?

> @aurelien-reeves do you mean that users won't be able to run scenarios with cucumber-js?
>
> The FakeBrowsers.js API does not depend on electron. It does however depend on the DOM, via the document global object. They could use jsdom for this if they want to.

The code requires to be adapt to be executed on cucumber-electron or cucumber-js, but maybe this is not an issue.

**Comment by jbpros** [comment]
This is great!

Something that might need emphasis in the documentation is that it won't fly for some full-fledged multi-session scenarios. As we're dealing with a single browser window/DOM, there is no way, for example, to log two separate users. They would share the same browser session (cookies, localStorage, etc.), making it impossible to tell them apart. A single-page app with some global state (boo!) would also not work in this environment. 

It seems we have a candidate for another feature in this API: multiple real browsers ;)

**Comment by aslakhellesoy** [comment]
> I mean, is this a FakeBrowser API? With all that could be related to a browser like the window sizes, the possibility to scroll, to control the visible area, to take screenshots?

It's an API to insert a tiny bit of HTML into the DOM that looks like a fake browser (see screenshot). Nothing more.

**Comment by aslakhellesoy** [comment]
> Something that might need emphasis in the documentation is that it won't fly for some full-fledged multi-session scenarios. As we're dealing with a single browser window/DOM, there is no way, for example, to log two separate users. They would share the same browser session (cookies, localStorage, etc.), making it impossible to tell them apart. A single-page app with some global state (boo!) would also not work in this environment.

That's correct. When I use Cucumber-Electron I decouple all of the browser "infrastructure" from the React code I mount in the DOM (such as `fetch`, cookies, `localStorage`). When this is done properly, there is no problem having multiple independent users mounted in the same DOM. The React app I mount is assembled using non-infrastructure adapters.

I use dependency injection to inject non-infrastructure implementations for retrieving data, managing session state, storing local data etc.

These are general decoupling techniques that we should document.

**Review by romaingweb — APPROVED** [review]

**Comment by aurelien-reeves** [comment]
> 
> 
> > I mean, is this a FakeBrowser API? With all that could be related to a browser like the window sizes, the possibility to scroll, to control the visible area, to take screenshots?
> 
> It's an API to insert a tiny bit of HTML into the DOM that looks like a fake browser (see screenshot). Nothing more.

As a user, if I see an API named "FakeBrowser", I expect more than a DOM container where I can inject some HTML.

So I suggest renaming the API from FakeBrowser to something like "DOMContainer".

**Comment by aslakhellesoy** [comment]
Thanks for the feedback everyone. I've renamed the API to `AppElements`. The word `App` is meant to convey that this is where you should mount your app (or component). The word `Elements` is a reference to the DOM API - nodes are of type [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element).

**Pull request merged**
